ALTER TABLE "Experience" ADD COLUMN "titleEn" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Experience" ADD COLUMN "subtitleEn" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Experience" ADD COLUMN "excerptEn" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Experience" ADD COLUMN "descriptionEn" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Experience" ADD COLUMN "highlightsEn" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[];

ALTER TABLE "Service" ADD COLUMN "titleEn" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Service" ADD COLUMN "excerptEn" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Service" ADD COLUMN "descriptionEn" TEXT NOT NULL DEFAULT '';

ALTER TABLE "Destination" ADD COLUMN "nameEn" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Destination" ADD COLUMN "regionEn" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Destination" ADD COLUMN "excerptEn" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Destination" ADD COLUMN "descriptionEn" TEXT NOT NULL DEFAULT '';

ALTER TABLE "Offer" ADD COLUMN "titleEn" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Offer" ADD COLUMN "destinationLabelEn" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Offer" ADD COLUMN "excerptEn" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Offer" ADD COLUMN "descriptionEn" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Offer" ADD COLUMN "badgeEn" TEXT NOT NULL DEFAULT '';

ALTER TABLE "Article" ADD COLUMN "titleEn" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Article" ADD COLUMN "excerptEn" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Article" ADD COLUMN "contentEn" TEXT NOT NULL DEFAULT '';

ALTER TABLE "Testimonial" ADD COLUMN "contentEn" TEXT NOT NULL DEFAULT '';

ALTER TABLE "Faq" ADD COLUMN "questionEn" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Faq" ADD COLUMN "answerEn" TEXT NOT NULL DEFAULT '';

ALTER TABLE "GalleryItem" ADD COLUMN "titleEn" TEXT NOT NULL DEFAULT '';
ALTER TABLE "GalleryItem" ADD COLUMN "captionEn" TEXT NOT NULL DEFAULT '';
